### ISSUE TITLE
Add package documentation

### ISSUE THREAD

**Issue by auricsystems** [AuricSystemsInternational/creditcard-validator#3]
elm-package requires Module documentation before a package can be published. 

Documentation guidelines: http://package.elm-lang.org/help/documentation-format

**Comment by sd0s** [comment]
I think I've made all the updates necessary to enable publication to elm package. The documentation generated with elm-make passes the elm-package documentation preview validation. I'm going to create a PR to merge to develop branch. Then it needs a second merge to master branch before thinks can be published to elm-package.
